<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="75522" started-at="2018-02-04T17:54:09Z" finished-at="2018-02-04T17:55:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="75522" started-at="2018-02-04T17:54:09Z" finished-at="2018-02-04T17:55:25Z">
      <class name="c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage">
        <test-method status="PASS" signature="setup()[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2]" name="setup" is-config="true" duration-ms="15825" started-at="2018-02-04T23:24:09Z" finished-at="2018-02-04T23:24:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2]" name="beforeMethod" is-config="true" duration-ms="11" started-at="2018-02-04T23:24:25Z" finished-at="2018-02-04T23:24:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage.verifyGrandTotalValues() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyGrandTotalValues()[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2]" name="verifyGrandTotalValues" duration-ms="55773" started-at="2018-02-04T23:24:25Z" finished-at="2018-02-04T23:25:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [554.86] but found [560.36]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [554.86] but found [560.36]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage.verifyGrandTotalValues(TC_003_VerifyValuesFromRFOtoOrderConfirmedPage.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGrandTotalValues -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2]" name="afterMethod" is-config="true" duration-ms="685" started-at="2018-02-04T23:25:21Z" finished-at="2018-02-04T23:25:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyGrandTotalValues status=FAILURE method=TC_003_VerifyValuesFromRFOtoOrderConfirmedPage.verifyGrandTotalValues()[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage@176d53b2]" name="endTest" is-config="true" duration-ms="3173" started-at="2018-02-04T23:25:22Z" finished-at="2018-02-04T23:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- c2info_OrderBuk_IntegrationSuiteTCs.TC_003_VerifyValuesFromRFOtoOrderConfirmedPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
